### ISSUE TITLE
Add interface for simplex operations

### ISSUE THREAD

**Issue by wotzlaff** [bradfordboyle/pyglpk#33]
Do you see any chance to implement an interface to `lpx_eval_tab_row` and `lpx_eval_tab_col`?
Up to now, the [docs](https://pyglpk.readthedocs.io/en/latest/brief-reference.html#manual-simplex-tableau-operations) says that probably no one would need it, but I think I got a use case.

**Comment by bradfordboyle** [comment]
I finally got a chance to look at this and I have a [feature branch](https://github.com/bradfordboyle/pyglpk/tree/add-simplex-tableau-routines) with a draft implementation. I will need to add some doc strings for the new methods and test coverage as well.

**Comment by wotzlaff** [comment]
Great! Thank you very much for the quick and positive reply. I did not expect to get a reaction so soon :)
This seems to work. I will give it a try and might produce some tests if you like.

**Comment by wotzlaff** [comment]
One problem that I see so far is that the indices for these methods are really hard to handle: They start from 1 and have different meanings (auxiliary or structural variable) for different index ranges. This makes using it not very intuitive.
One possibility to make it easier (at least somehow) would be to add helper functions to the rows and columns (which should know their true index). But I is not obvious how to transform the return value. (Maybe two lists: one for aux and one for struct vars?)
Of course, one could say that everyone who's using the method needs to look up the documentation anyway. So this is no big deal.

Another problem is that an internal error is thrown if one tries to apply the methods to non-basic variables. The program then terminates. It would be nice to raise an exception in this case instead.

**Comment by bradfordboyle** [comment]
Thanks for testing this out and for the feedback!

> Another problem is that an internal error is thrown if one tries to apply the methods to non-basic variables. The program then terminates. It would be nice to raise an exception in this case instead.

I noticed this when I was working on adding in the new methods. The GLPK API doesn't make it easy to intercept errors; it looks like there are two options:

1. Copy the error condition checks from the method into the Python C API and return an exception before calling in to the GLPK API
2. Make use of `glp_error_hook` to intercept the errors on the C API and skip over the hard-coded calls to `abort()` & `exit()`

To help speed up iteration, I'll probably go with the first option (which isn't great because it tightly couples the wrapping to the internals of GLPK). I might look at option 2 as a separate issue.

> One problem that I see so far is that the indices for these methods are really hard to handle

It has been a while since I've had to look at the math behind the simplex method and the internals of GLPK. Your suggestion should be doable but it might take some iterations to get a more pythonic interface.

**Comment by bradfordboyle** [comment]
I've hacked some more and I have an updated API. I've moved `eval_tab_row()` and `eval_tab_col()` to the corresponding object for rows and columns. I've included a basic [test suite](https://github.com/bradfordboyle/pyglpk/blob/add-simplex-tableau-routines/tests/tableau_test.py) for coverage and demonstrating the API.

While working on this code, I realized that I had made an error in implementing `transform_row` and `transform_col`, so I have removed them from the `LPX` object for now.

**Comment by wotzlaff** [comment]
This seems to be the better interface. At least now the meaning of the indices (which no longer exist explicitly) is clear.
Now I get a `free(): invalid next size (fast)` from [here](https://github.com/bradfordboyle/pyglpk/commit/9a397fbae0d671ea51ff1dabe9773f8f23181544#diff-aad6052ef6c3abcc4c1971e8fdf36d25e320e77c6426d731bf9aee6042992381R588). This is probably because it should be `m` instead of `n` [here](https://github.com/bradfordboyle/pyglpk/commit/9a397fbae0d671ea51ff1dabe9773f8f23181544#diff-aad6052ef6c3abcc4c1971e8fdf36d25e320e77c6426d731bf9aee6042992381R567-R568).
